---
flower_python_package_name: flower
flower_python_package_version: 1.2.0

flower_python_version: python39
flower_python_main: python3
flower_pip_version: python3-pip

flower_user: galaxy
flower_group: galaxy

flower_app_dir: ""
flower_app_name: ""
flower_venv_dir: "/home/{{ flower_user }}/.local"
flower_python_path: ""
flower_galaxy_conf: "{{ galaxy_root }}/config/galaxy.yml"

flower_log_file: /var/log/flower
flower_conf_dir: /etc/flower

flower_mem_limit: 2G

flower_bind_address: 0.0.0.0
flower_port: 5555
flower_broker_api: ""
flower_persistent: "False"
flower_db_file: "flower" # https://flower.readthedocs.io/en/latest/config.html#db

flower_broker_url: ""

flower_ui_users:
  - name: guest
    password: guest

flower_state: started
flower_enabled: yes
flower_environment_variables: []
# flower_proxy_prefix: /flower
