---
galaxy_info:
  role_name: flower
  namespace: usegalaxy_eu
  author: Mira Kuntz
  description: Installs Flower, a web UI for Celery
  company: Galaxy Project
  license: Apache
  min_ansible_version: 1.2
  platforms:
    - name: Centos, RHEL, Fedora, Rocky Linux, Ubuntu
      versions:
        - all
        - trusty
dependencies: []
