---
# defaults file for sentry_selfhosted

sentry_docker_compose_project_folder: /opt/docker/sentry
sentry_version: 23.3.1
sentry_bind: 9000

sentry_env: {}
sentry_mail: {}
sentry_config: {}

sentry_url:
sentry_superusers: []
