name: ci

on: [push, pull_request]

jobs:

  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Copy files to test instance and preserve secrets and hosts
        run: |
          rsync -rav * debian@usegalaxy-test.cerit-sc.cz:~/usegalaxy-${{ steps.date.outputs.date }}
          ssh debian@usegalaxy-test.cerit-sc.cz 'cp ~/usegalaxy/hosts ~/usegalaxy-${{ steps.date.outputs.date }}'
          ssh debian@usegalaxy-test.cerit-sc.cz 'cp ~/usegalaxy/.vault-password.txt ~/usegalaxy-${{ steps.date.outputs.date }}'
          ssh debian@usegalaxy-test.cerit-sc.cz 'cp ~/usegalaxy/group_vars/secret.yml ~/usegalaxy-${{ steps.date.outputs.date }}/group_vars'
      - name: Run playbook
        run: |
          ssh debian@usegalaxy-test.cerit-sc.cz 'cd ~/usegalaxy-${{ steps.date.outputs.date }} && ansible-galaxy install -p roles -r requirements.yml'
          ssh debian@usegalaxy-test.cerit-sc.cz 'cd ~/usegalaxy-${{ steps.date.outputs.date }} && ansible-playbook galaxy.yml'
