#! vim: ts=2 expandtab:

name: deploy-dev

# TODO: run automatically on push to main
on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call common
        uses: ./.github/actions/deploy-common
        env:
          TARGET_HOSTNAME: mu-pub-245-177.flt.openstack.cloud.e-infra.cz
          TARGET_USER: debian
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD_DEV }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
